### ISSUE TITLE
wiring

### ISSUE THREAD

**Issue by gemyo1** [projectswithalex/Reaction-Lights-Training-Module#1]
hello,
thanks for this project.
can you make a document with the wiring on the differents electronics cards please
I want to make my own reaction light but I'm a noob with this cards.

thank you very much

**Comment by TheprofessionalKhaled** [comment]
you are right ...the wiring is missing with the appropiate values resisters in the power circuit ..and the proper connection of the sensor

**Comment by gemyo1** [comment]
Thanks for the answer, i look forward for the wiring.
;-)

**Comment by TheprofessionalKhaled** [comment]
I already message alex directly on his mail asking him for the wiring ....I
hope he reply to it

**Comment by projectswithalex** [comment]
Updated "Schematic" (Visual Representation) of the connections for Agility Lights.  (commit #38c155d )

**Comment by gemyo1** [comment]
Thanks very much,
It will be very helpful !

Le jeu. 28 sept. 2023, 23:36, projectswithalex ***@***.***> a
écrit :

**Comment by TheprofessionalKhaled** [comment]
thanks man I appreciate that
